Armory = {}

Armory.AssignedLoadouts = { -- items accessable in shop
	["police"] = {
		{item = "breaching_charge", flag = "firearms", level = 2, price = 10000, label = "Breaching Charge", type = "item_standard"},
		{item = "idcard", flag = "taser", level = 0, price = 0, label = "ID Card", type = "item_standard"},
		{item = "radio", flag = "taser", level = 0, price = 0, label = "Service Radio", type = "item_standard"},
		{item = "phone", flag = "taser", level = 0, price = 250, label = "SmartPhone", type = "item_standard"},
		{item = "binoculars", flag = "taser", level = 0, price = 0, label = "Binoculars", type = "item_standard"},
		{item = "repairkit", flag = "taser", level = 0, price = 250, label = "Repair Kit", type = "item_standard"},
		{item = "armor", flag = "taser", level = 0, price = 200, label = "Armor", type = "item_standard"},
		{item = "scuba", flag = "boat", level = 1, price = 80, label = "Oxygen Tank", type = "item_standard"},
		{item = "pistol", flag = "firearms", level = 1, price = 100, label = "Pistol Ammo", type = "item_ammo"},
		{item = "smg", flag = "firearms", level = 2, price = 125, label = "SMG Ammo", type = "item_ammo"},
		{item = "assaultRifle", flag = "firearms", level = 3, price = 150, label = "Rifle Ammo", type = "item_ammo"},
		{item = "sniper", flag = "firearms", level = 4, price = 200, label = "Sniper Ammo", type = "item_ammo"},
		{item = "beanBag", flag = "firearms", level = 2, price = 20, label = "Baton Launcher Ammo", type = "item_ammo"},
		{item = "WEAPON_FLASHLIGHT", flag = "taser", level = 0, price = 0, label = "Flashlight", type = "item_weapon"},
		{item = "WEAPON_NIGHTSTICK", flag = "taser", level = 0, price = 0, label = "ASP", type = "item_weapon"},
		{item = "WEAPON_STUNGUN", flag = "taser", level = 1, price = 250, label = "Taser", type = "item_weapon"},
		{item = "WEAPON_PISTOL", flag = "firearms", level = 1, price = 2500, label = "Pistol", type = "item_weapon"},
		{item = "WEAPON_COMBATPISTOL", flag = "firearms", level = 1, price = 4000, label = "Combat Pistol", type = "item_weapon"},
		{item = "WEAPON_SMG", flag = "firearms", level = 2, price = 6000, label = "SMG", type = "item_weapon"},
		{item = "WEAPON_SPECIALCARBINE", flag = "firearms", level = 3, price = 7500, label = "Special Carbine", type = "item_weapon"},
		{item = "WEAPON_CARBINERIFLE_MK2", flag = "firearms", level = 4, price = 8000, label = "Carbine MKII", type = "item_weapon"},
		{item = "WEAPON_SNIPERRIFLE", flag = "firearms", level = 4, price = 10000, label = "Operations Sniper Rifle", type = "item_weapon"},
		{item = "WEAPON_GRENADELAUNCHER", flag = "firearms", level = 2, price = 4000, label = "Baton Launcher", type = "item_weapon"},
	},
	["ambulance"] = {
		{item = "idcard", flag = "firstaid", level = 0, price = 0, label = "ID Card", type = "item_standard"},
		{item = "binoculars", flag = "firstaid", level = 0, price = 0, label = "Binoculars", type = "item_standard"},
		{item = "radio", flag = "firstaid", level = 0, price = 0, label = "Service Radio", type = "item_standard"},
		{item = "phone", flag = "firstaid", level = 0, price = 500, label = "SmartPhone", type = "item_standard"},
		{item = "armor", flag = "firstaid", level = 0, price = 350, label = "Armor", type = "item_standard"},
		{item = "WEAPON_FLASHLIGHT", flag = "firstaid", level = 0, price = 0, label = "Flashlight", type = "item_weapon"},
		{item = "bandage", flag = "firstaid", level = 0, price = 0, label = "Bandage", type = "item_standard"},
		{item = "paracetamol", flag = "firstaid", level = 0, price = 0, label = "Paracetamol", type = "item_standard"},
		{item = "comp_drug_morphine", flag = "firstaid", level = 0, price = 0, label = "Morphine", type = "item_standard"},
		{item = "repairkit", flag = "firstaid", level = 0, price = 150, label = "Repair Kit", type = "item_standard"},
		{item = "scuba", flag = "firstaid", level = 0, price = 80, label = "Oxygen Tank", type = "item_standard"},
	},
	["gruppe6"] = {
		{item = "idcard", flag = "gruppe6", level = 1, price = 0, label = "ID Card", type = "item_standard"},
		{item = "radio", flag = "gruppe6", level = 1, price = 0, label = "Service Radio", type = "item_standard"},
		{item = "phone", flag = "gruppe6", level = 1, price = 500, label = "SmartPhone", type = "item_standard"},
		{item = "binoculars", flag = "gruppe6", level = 1, price = 0, label = "Binoculars", type = "item_standard"},
		{item = "pistol", flag = "gruppe6", level = 2, price = 100, label = "Pistol Ammo", type = "item_ammo"},
		{item = "beanBag", flag = "gruppe6", level = 2, price = 10, label = "Baton Launcher Ammo", type = "item_ammo"},
		{item = "WEAPON_FLASHLIGHT", flag = "gruppe6", level = 1, price = 0, label = "Flashlight", type = "item_weapon"},
		{item = "WEAPON_NIGHTSTICK", flag = "gruppe6", level = 1, price = 0, label = "ASP", type = "item_weapon"},
		{item = "armor", flag = "gruppe6", level = 1, price = 100, label = "Armor", type = "item_standard"},
		{item = "WEAPON_STUNGUN", flag = "gruppe6", level = 2, price = 0, label = "Taser", type = "item_weapon"},
		{item = "WEAPON_PISTOL", flag = "gruppe6", level = 2, price = 0, label = "Pistol", type = "item_weapon"},
		{item = "WEAPON_GRENADELAUNCHER", flag = "gruppe6", level = 2, price = 0, label = "Baton Launcher", type = "item_weapon"},
	},
}