h_Config 				  = {}
h_Config.CooldownPolice = 700
h_Config.cooldown		  = 1700

-- Add/remove weapon hashes here to be added for holster checks.
h_Config.Weapons = {
	"weapon_dagger",
	"weapon_bat",
	"weapon_crowbar",
	"weapon_flashlight",
	"weapon_golfclub",
	"weapon_hammer",
	"weapon_hatchet",
	"weapon_knife",
	"weapon_machete",
	"weapon_nightstick",
	"weapon_wrench",
	"weapon_battleaxe",
	"weapon_poolcue",
	"weapon_stone_hatchet",
	"weapon_pistol",
	"weapon_pistol_mk2",
	"weapon_combatpistol",
	"weapon_appistol",
	"weapon_stungun",
	"weapon_pistol50",
	"weapon_snspistol",
	"weapon_snspistol_mk2",
	"weapon_heavypistol",
	"weapon_vintagepistol",
	"weapon_flaregun",
	"weapon_marksmanpistol",
	"weapon_revolver",
	"weapon_revolver_mk2",
	"weapon_doubleaction",
	"weapon_raypistol",
	"weapon_ceramicpistol",
	"weapon_navyrevolver",
	"weapon_machinepistol",
	"weapon_minismg",
	"WEAPON_GROVEM1911",
	"WEAPON_BALLAM1911",
	"WEAPON_VAGOSM1911",
	"WEAPON_MARAGRANDEM1911",
	"WEAPON_AZTECAM1911",
	"WEAPON_TRIADSM1911",

}

h_Config.BigWeapons = {
	"weapon_microsmg",
	"weapon_smg",
	"weapon_smg_mk2",
	"weapon_assaultsmg",
	"weapon_combatpdw",
	"weapon_raycarbine",
	"weapon_pumpshotgun",
	"weapon_pumpshotgun_mk2",
	"weapon_sawnoffshotgun",
	"weapon_assaultshotgun",
	"weapon_bullpupshotgun",
	"weapon_musket",
	"weapon_heavyshotgun",
	"weapon_dbshotgun",
	"weapon_autoshotgun",
	--Assault Rifles
	"weapon_assaultrifle",
	"weapon_assaultrifle_mk2",
	"weapon_carbinerifle",
	"weapon_carbinerifle_mk2",
	"weapon_advancedrifle",
	"weapon_specialcarbine",
	"weapon_specialcarbine_mk2",
	"weapon_bullpuprifle",
	"weapon_bullpuprifle_mk2",
	"weapon_compactrifle",
	-- LMGS
	"weapon_mg",
	"weapon_combatmg",
	"weapon_combatmg_mk2",
	"weapon_gusenberg",
	-- Snipers
	"weapon_sniperrifle",
	"weapon_heavysniper",
	"weapon_heavysniper_mk2",
	"weapon_marksmanrifle",
	"weapon_marksmanrifle_mk2",
	-- Heavys
	"weapon_rpg",
	"weapon_grenadelauncher",
	"weapon_grenadelauncher_smoke",
	"weapon_minigun",
	"weapon_firework",
	"weapon_railgun",
	"weapon_hominglauncher",
	"weapon_compactlauncher",
	"weapon_rayminigun",
	-- Throwables
	"weapon_grenade",
	"weapon_bzgas",
	"weapon_molotov",
	"weapon_stickybomb",
	"weapon_proxmine",
	"weapon_snowball",
	"weapon_pipebomb",
	"weapon_ball",
	"weapon_smokegrenade",
	"weapon_flare",
	-- Misc
	"weapon_petrolcan",
	"gadget_parachute",
	"weapon_fireextinguisher",
	"weapon_hazardcan",
}
