ds = {}

ds.discord = { -- webhook details
	address = "https://discord.gg/roleplay",
	webhook = "https://discordapp.com/api/webhooks/720371172788666439/k35n_8ApddFzgPTCcU0pDbl8rcRzLVmhLwUN-KGy_M0HmYZcAqYRDlvZFSFDqrlr6AuM",
	screenURL = "",
}

ds.maxEntitesCreatedPerSecond = 50
ds.maxWarningPoints = 5

ds.entityTypeLabels = {
	[0] = "No entity",
	[1] = "Ped",
	[2] = "Vehicle",
	[3] = "Object",
}

ds.explosionTypes = {
	[1] = {name = 'EXPLOSION_GRENADE', blacklisted = false},
	[2] = {name = 'EXPLOSION_GRENADELAUNCHER', blacklisted = true},
	[3] = {name = 'EXPLOSION_STICKYBOMB', blacklisted = false},
	[4] = {name = 'EXPLOSION_MOLOTOV', blacklisted = true},
	[5] = {name = 'EXPLOSION_ROCKET', blacklisted = true},
	[6] = {name = 'EXPLOSION_TANKSHELL', blacklisted = false},
	[7] = {name = 'EXPLOSION_HI_OCTANE', blacklisted = false},
	[8] = {name = 'EXPLOSION_CAR', blacklisted = false},
	[9] = {name = 'EXPLOSION_PLANE', blacklisted = false},
	[10] = {name = 'EXPLOSION_PETROL_PUMP', blacklisted = false},
	[11] = {name = 'EXPLOSION_BIKE', blacklisted = false},
	[12] = {name = 'EXPLOSION_DIR_STEAM', blacklisted = false},
	[13] = {name = 'EXPLOSION_DIR_FLAME', blacklisted = false},
	[14] = {name = 'EXPLOSION_DIR_WATER_HYDRANT', blacklisted = false},
	[15] = {name = 'EXPLOSION_DIR_GAS_CANISTER', blacklisted = false},
	[16] = {name = 'EXPLOSION_BOAT', blacklisted = false},
	[17] = {name = 'EXPLOSION_SHIP_DESTROY', blacklisted = false},
	[18] = {name = 'EXPLOSION_TRUCK', blacklisted = false},
	[19] = {name = 'EXPLOSION_BULLET', blacklisted = false},
	[20] = {name = 'EXPLOSION_SMOKEGRENADELAUNCHER', blacklisted = false},
	[21] = {name = 'EXPLOSION_SMOKEGRENADE', blacklisted = false},
	[22] = {name = 'EXPLOSION_BZGAS', blacklisted = false},
	[23] = {name = 'EXPLOSION_FLARE', blacklisted = false},
	[24] = {name = 'EXPLOSION_GAS_CANISTER', blacklisted = false},
	[25] = {name = 'EXPLOSION_EXTINGUISHER', blacklisted = false},
	[26] = {name = 'EXPLOSION_PROGRAMMABLEAR', blacklisted = false},
	[27] = {name = 'EXPLOSION_TRAIN', blacklisted = false},
	[28] = {name = 'EXPLOSION_BARREL', blacklisted = false},
	[29] = {name = 'EXPLOSION_PROPANE', blacklisted = false},
	[30] = {name = 'EXPLOSION_BLIMP', blacklisted = false},
	[31] = {name = 'EXPLOSION_DIR_FLAME_EXPLODE', blacklisted = false},
	[32] = {name = 'EXPLOSION_TANKER', blacklisted = true},
	[33] = {name = 'EXPLOSION_PLANE_ROCKET', blacklisted = false},
	[34] = {name = 'EXPLOSION_VEHICLE_BULLET', blacklisted = false},
	[35] = {name = 'EXPLOSION_GAS_TANK', blacklisted = false},
	[36] = {name = 'EXPLOSION_BIRD_CRAP', blacklisted = false}
}

ds.reasons = { -- webhook reasons
	chatspam = {dev = "Illegal Chat Entry", staff = "Player has used an illegal chat entry, found within many skiddie menus. Used to spam the chat. OR used N word in a chat."},
	chat_ban = {dev = "Illegal Chat Entry", staff = "Player broke community rule 1.2 in chat"},
	explosion = {dev = "Illegal Network Event: 0", staff = "Player has either spawned an illegal explosion or has had an illegal explosion spawned on them."},
	exp_large = {dev = "Illegal Network Event: 2", staff = "Unusually large networked explosion (Usually caused by a script or large explosion)"},
	exp_illegal = {dev = "Illegal Network Event: 3", staff = "Illegally networked explosion (Always caused by a script) The identified player has a chance of being a skiddie but worth investigating."},
	blacklistedweapon = {dev = "Illegal Network Event: 4", staff = "Someone has spawned an illegal weapon on this player. The identified player has a chance of spawning in weapon but worth pairing with other trigger information eg: Weapon Give Event as that will identifiy who spawned the weapon, this event just tells you who recieved the weapon and why their loadout was cleared."},
	blacklistedvehicle = {dev = "Illegal Network Event: 5", staff = "Player has managed to get into a vehicle that doesn't spawn and it's blacklisted. The identified player has a chance of being a skiddie but worth investigating."},
	illegal6 = {dev = "Silent Event Trigger: 6", staff = "See development lead / management for more information"},
	blacklistednumberplate = {dev = "Silent Event Trigger: 7", staff = "Player has set off a silent trigger. This is a good indicator of an illegal menu. This data should be paired with something else.\nA skiddie is definitely on the server."},
	fakeevent = {dev = "Illegal Network Event: 8", staff = "Player triggered an event that is present on majority of other servers which used to redeem/payout money, items etc from a job"},
	healthviolation1 = {dev = "Silent Detection: 9", staff = "Player has failed the health regen check. Keep a lookout. Repeated triggers of this event within a short period of time is good evidence.\nOnly time this will false flag is if player has been revived/respawned as it triggered"},
	healthviolation2 = {dev = "Silent Detection: 10", staff = "Health pool check failed, the player has a greater than 400 health pool (Not possible without script)"},
	healthviolation3 = {dev = "Silent Detection: 11", staff = "Player has failed an invincibility check. Keep a lookout. Repeated triggers of this event within a short period of time is good evidence.\nOnly time this will false flag is if the player is currently downed"},
	recviol = {dev = "Silent Detection: 12", staff = "See development lead / management for more information"},
	vehmodelswitch = {dev = "RPUK Garages Event: 13", staff = "Players has entered a vehicle into the garage with a switched model hash. This doesn't mean they are using an illegal client/cheat engine 100%, but are likely cooperating with one or have access to one.\nEvidence should be paired with logs and other stuff before issuing a ban for this."},
	job_restricted = {dev = "RPUK Jobs Event: 14", staff = "Attempted to trigger an event without meeting requirements. Script exec menu."},
	illegal15 = {dev = "Silent Event Trigger: 15", staff = "See development lead / management for more information"}, -- ESX Basic call - we use a modified version
	illegal16 = {dev = "Silent Event Trigger: 16", staff = "See development lead / management for more information"},
	decoy_harvest = {dev = "Client dumping / reading source code for locations", staff = "Player is client dumping / data mining for locations."}, -- They have triggered a hidden decoy.
	give_weapon = {dev = "Weapon Give Event", staff = "Player attempted to spawn a weapon on another player, in a way that is not allowed"},

	bl_entity_created = {dev = "Blacklisted Entity Created", staff = "A blacklisted entity was created, there's a chance that the stated player spawned it. Our code should never call this event."},
	bl_entity_denied_creation = {dev = "Blacklisted Entity Denied Creation", staff = "A blacklisted entity was not allowed to spawn, there's a chance that the stated player spawned it."},
	clear_ped_task = {dev = "CClearPedTasksEvent", staff = "Player attempted to clear another players tasks, mostly an attempt to kick someone (or the entire server) from their current vehicle."},
	player_entity_limit = {dev = "Player Entity Spawn Limit", staff = "Player has spawned more than 50 entities within a second, keep a lookout. The identified player has a chance of being a skiddie, but getting the ownership in FiveM is not reliable."},
	threat_level_max = {dev = "Threat Level Max Hit", staff = "Player has reached the threat max level and is most likely a skiddie, keep a lookout."},
	shopLocationExploit = {dev = "RPUK shop safe exploit", staff = "Player has triggerd the 'collectMoney' event without being close to a safe."},
	taxi_timeout = {dev = "Taxi Payout Warning", staff = "Player has triggered the 'payout' event more than once within 20 seconds. He is probably cheating."},
	house_dupe_exploit = {dev = "Inventory Lag/Exploit", staff = "Player has been stopped duplicating items, this might be intentional or can be caused by a bad player connection. (Also possible attempt is by pulling plug on internet) Please keep a look out."},
}

ds.bobj = { -- blacklisted objects
	[GetHashKey("dt1_tc_dufo_core")] = true,
	[GetHashKey("dt1_tc_ufocore")] = true,
	[GetHashKey("imp_prop_ship_01a")] = true,
	[GetHashKey("prop_fnclink_05c")] = true,
	[GetHashKey("prop_fnclink_05crnr1")] = true,
	[GetHashKey("prop_fnclink_05d")] = true,
	[GetHashKey("xs_prop_hamburgher_wl")] = true,
	[GetHashKey("prop_dog_cage_02")] = true,
	[GetHashKey("prop_beach_fire")] = true,
	[GetHashKey("prop_gold_cont_01")] = true,
	[GetHashKey("p_cablecar_s")] = true,
	[GetHashKey("sr_prop_spec_tube_crn_05a")] = true,
	[GetHashKey("sr_prop_spec_tube_crn_30d_05a")] = true,
	[GetHashKey("sr_prop_spec_tube_l_05a")] = true,
	[GetHashKey("sr_prop_spec_tube_m_05a")] = true,
	[GetHashKey("sr_prop_spec_tube_xxs_05a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn_15d_05a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn_5d_05a")] = true,
	[GetHashKey("sr_prop_stunt_tube_xs_05a")] = true,
	[GetHashKey("sr_prop_special_bblock_lrg11")] = true,
	[GetHashKey("sr_prop_special_bblock_lrg2")] = true,
	[GetHashKey("sr_prop_special_bblock_lrg3")] = true,
	[GetHashKey("sr_prop_special_bblock_mdm1")] = true,
	[GetHashKey("sr_prop_special_bblock_mdm2")] = true,
	[GetHashKey("sr_prop_special_bblock_mdm3")] = true,
	[GetHashKey("sr_prop_special_bblock_sml1")] = true,
	[GetHashKey("sr_prop_special_bblock_sml2")] = true,
	[GetHashKey("sr_prop_special_bblock_sml3")] = true,
	[GetHashKey("sr_prop_special_bblock_xl1")] = true,
	[GetHashKey("sr_prop_special_bblock_xl2")] = true,
	[GetHashKey("sr_prop_special_bblock_xl3")] = true,
	[GetHashKey("sr_prop_special_bblock_xl3_fixed")] = true,
	[GetHashKey("sr_prop_sr_target_1_01a")] = true,
	[GetHashKey("sr_prop_sr_target_2_04a")] = true,
	[GetHashKey("sr_prop_sr_target_3_03a")] = true,
	[GetHashKey("sr_prop_sr_target_5_01a")] = true,
	[GetHashKey("sr_prop_sr_target_large_01a")] = true,
	[GetHashKey("sr_prop_sr_target_long_01a")] = true,
	[GetHashKey("sr_prop_sr_target_small_01a")] = true,
	[GetHashKey("sr_prop_sr_target_small_02a")] = true,
	[GetHashKey("sr_prop_sr_target_small_03a")] = true,
	[GetHashKey("sr_prop_sr_target_small_04a")] = true,
	[GetHashKey("sr_prop_sr_target_small_05a")] = true,
	[GetHashKey("sr_prop_sr_target_small_06a")] = true,
	[GetHashKey("sr_prop_sr_target_small_07a")] = true,
	[GetHashKey("sr_prop_sr_target_trap_01a")] = true,
	[GetHashKey("sr_prop_sr_target_trap_02a")] = true,
	[GetHashKey("sr_prop_sr_track_block_01")] = true,
	[GetHashKey("sr_prop_sr_track_wall")] = true,
	[GetHashKey("sr_prop_sr_tube_end")] = true,
	[GetHashKey("sr_prop_sr_tube_wall")] = true,
	[GetHashKey("sr_prop_spec_target_b_01a")] = true,
	[GetHashKey("sr_prop_spec_target_m_01a")] = true,
	[GetHashKey("sr_prop_spec_target_s_01a")] = true,
	[GetHashKey("sr_prop_spec_tube_refill")] = true,
	[GetHashKey("sr_prop_track_refill")] = true,
	[GetHashKey("sr_prop_track_refill_t1")] = true,
	[GetHashKey("sr_prop_track_refill_t2")] = true,
	[GetHashKey("sr_mp_spec_races_ammu_sign")] = true,
	[GetHashKey("sr_mp_spec_races_blimp_sign")] = true,
	[GetHashKey("sr_mp_spec_races_ron_sign")] = true,
	[GetHashKey("sr_mp_spec_races_xero_sign")] = true,
	[GetHashKey("sr_prop_sr_start_line_02")] = true,
	[GetHashKey("sr_prop_track_straight_l_d15")] = true,
	[GetHashKey("sr_prop_track_straight_l_d30")] = true,
	[GetHashKey("sr_prop_track_straight_l_d45")] = true,
	[GetHashKey("sr_prop_track_straight_l_d5")] = true,
	[GetHashKey("sr_prop_track_straight_l_u15")] = true,
	[GetHashKey("sr_prop_track_straight_l_u30")] = true,
	[GetHashKey("sr_prop_track_straight_l_u45")] = true,
	[GetHashKey("sr_prop_track_straight_l_u5")] = true,
	[GetHashKey("sr_prop_spec_tube_crn_01a")] = true,
	[GetHashKey("sr_prop_spec_tube_crn_30d_01a")] = true,
	[GetHashKey("sr_prop_spec_tube_l_01a")] = true,
	[GetHashKey("sr_prop_spec_tube_m_01a")] = true,
	[GetHashKey("sr_prop_spec_tube_s_01a")] = true,
	[GetHashKey("sr_prop_spec_tube_xxs_01a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn_15d_01a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn_5d_01a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn2_01a")] = true,
	[GetHashKey("sr_prop_stunt_tube_xs_01a")] = true,
	[GetHashKey("sr_prop_spec_tube_crn_03a")] = true,
	[GetHashKey("sr_prop_spec_tube_crn_30d_03a")] = true,
	[GetHashKey("sr_prop_spec_tube_l_03a")] = true,
	[GetHashKey("sr_prop_spec_tube_m_03a")] = true,
	[GetHashKey("sr_prop_spec_tube_s_03a")] = true,
	[GetHashKey("sr_prop_spec_tube_xxs_03a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn_15d_03a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn_5d_03a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn2_03a")] = true,
	[GetHashKey("sr_prop_stunt_tube_xs_03a")] = true,
	[GetHashKey("sr_prop_spec_tube_crn_02a")] = true,
	[GetHashKey("sr_prop_spec_tube_crn_30d_02a")] = true,
	[GetHashKey("sr_prop_spec_tube_l_02a")] = true,
	[GetHashKey("sr_prop_spec_tube_m_02a")] = true,
	[GetHashKey("sr_prop_spec_tube_s_02a")] = true,
	[GetHashKey("sr_prop_spec_tube_xxs_02a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn_15d_02a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn_5d_02a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn2_02a")] = true,
	[GetHashKey("sr_prop_stunt_tube_xs_02a")] = true,
	[GetHashKey("sr_prop_spec_tube_crn_04a")] = true,
	[GetHashKey("sr_prop_spec_tube_crn_30d_04a")] = true,
	[GetHashKey("sr_prop_spec_tube_l_04a")] = true,
	[GetHashKey("sr_prop_spec_tube_m_04a")] = true,
	[GetHashKey("sr_prop_spec_tube_s_04a")] = true,
	[GetHashKey("sr_prop_spec_tube_xxs_04a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn_15d_04a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn_5d_04a")] = true,
	[GetHashKey("sr_prop_stunt_tube_crn2_04a")] = true,
	[GetHashKey("sr_prop_stunt_tube_xs_04a")] = true,
	[GetHashKey("stt_prop_race_tannoy")] = true,
	[GetHashKey("stt_prop_speakerstack_01a")] = true,
	[GetHashKey("stt_prop_flagpole_1c")] = true,
	[GetHashKey("stt_prop_flagpole_1e")] = true,
	[GetHashKey("stt_prop_flagpole_1d")] = true,
	[GetHashKey("stt_prop_flagpole_1f")] = true,
	[GetHashKey("stt_prop_flagpole_1a")] = true,
	[GetHashKey("stt_prop_flagpole_1b")] = true,
	[GetHashKey("stt_prop_flagpole_2a")] = true,
	[GetHashKey("stt_prop_flagpole_2b")] = true,
	[GetHashKey("stt_prop_flagpole_2c")] = true,
	[GetHashKey("stt_prop_flagpole_2d")] = true,
	[GetHashKey("stt_prop_flagpole_2e")] = true,
	[GetHashKey("stt_prop_flagpole_2f")] = true,
	[GetHashKey("stt_prop_corner_sign_01")] = true,
	[GetHashKey("stt_prop_corner_sign_02")] = true,
	[GetHashKey("stt_prop_corner_sign_03")] = true,
	[GetHashKey("stt_prop_corner_sign_04")] = true,
	[GetHashKey("stt_prop_corner_sign_05")] = true,
	[GetHashKey("stt_prop_corner_sign_06")] = true,
	[GetHashKey("stt_prop_corner_sign_07")] = true,
	[GetHashKey("stt_prop_corner_sign_08")] = true,
	[GetHashKey("stt_prop_corner_sign_09")] = true,
	[GetHashKey("stt_prop_corner_sign_10")] = true,
	[GetHashKey("stt_prop_corner_sign_11")] = true,
	[GetHashKey("stt_prop_corner_sign_12")] = true,
	[GetHashKey("stt_prop_corner_sign_13")] = true,
	[GetHashKey("stt_prop_corner_sign_14")] = true,
	[GetHashKey("stt_prop_hoop_constraction_01a")] = true,
	[GetHashKey("stt_prop_hoop_small_01")] = true,
	[GetHashKey("stt_prop_hoop_tyre_01a")] = true,
	[GetHashKey("stt_prop_race_gantry_01")] = true,
	[GetHashKey("stt_prop_race_start_line_01")] = true,
	[GetHashKey("stt_prop_race_start_line_01b")] = true,
	[GetHashKey("stt_prop_race_start_line_02")] = true,
	[GetHashKey("stt_prop_race_start_line_02b")] = true,
	[GetHashKey("stt_prop_race_start_line_03")] = true,
	[GetHashKey("stt_prop_race_start_line_03b")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
	[GetHashKey("stt_prop_ramp_adj_hloop")] = true,
	[GetHashKey("stt_prop_ramp_adj_loop")] = true,
	[GetHashKey("stt_prop_ramp_jump_l")] = true,
	[GetHashKey("stt_prop_ramp_jump_m")] = true,
	[GetHashKey("stt_prop_ramp_jump_s")] = true,
	[GetHashKey("stt_prop_ramp_jump_xl")] = true,
	[GetHashKey("stt_prop_ramp_jump_xs")] = true,
	[GetHashKey("stt_prop_ramp_jump_xxl")] = true,
	[GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
	[GetHashKey("stt_prop_ramp_spiral_m")] = true,
	[GetHashKey("stt_prop_ramp_spiral_s")] = true,
	[GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
	[GetHashKey("stt_prop_sign_circuit_01")] = true,
	[GetHashKey("stt_prop_sign_circuit_02")] = true,
	[GetHashKey("stt_prop_sign_circuit_03")] = true,
	[GetHashKey("stt_prop_sign_circuit_04")] = true,
	[GetHashKey("stt_prop_sign_circuit_05")] = true,
	[GetHashKey("stt_prop_sign_circuit_06")] = true,
	[GetHashKey("stt_prop_sign_circuit_07")] = true,
	[GetHashKey("stt_prop_sign_circuit_08")] = true,
	[GetHashKey("stt_prop_sign_circuit_09")] = true,
	[GetHashKey("stt_prop_sign_circuit_10")] = true,
	[GetHashKey("stt_prop_sign_circuit_11")] = true,
	[GetHashKey("stt_prop_sign_circuit_11b")] = true,
	[GetHashKey("stt_prop_sign_circuit_12")] = true,
	[GetHashKey("stt_prop_sign_circuit_13")] = true,
	[GetHashKey("stt_prop_sign_circuit_13b")] = true,
	[GetHashKey("stt_prop_sign_circuit_14")] = true,
	[GetHashKey("stt_prop_sign_circuit_14b")] = true,
	[GetHashKey("stt_prop_sign_circuit_15")] = true,
	[GetHashKey("stt_prop_slow_down")] = true,
	[GetHashKey("stt_prop_startline_gantry")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_01")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_02")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_03")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_04")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_05")] = true,
	[GetHashKey("stt_prop_stunt_bblock_hump_01")] = true,
	[GetHashKey("stt_prop_stunt_bblock_hump_02")] = true,
	[GetHashKey("stt_prop_stunt_bblock_lrg1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_lrg2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_lrg3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_mdm1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_mdm2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_mdm3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_qp")] = true,
	[GetHashKey("stt_prop_stunt_bblock_qp2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_qp3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_sml1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_sml2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_sml3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_xl1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_xl2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_xl3")] = true,
	[GetHashKey("stt_prop_stunt_bowling_ball")] = true,
	[GetHashKey("stt_prop_stunt_bowling_pin")] = true,
	[GetHashKey("stt_prop_stunt_bowlpin_stand")] = true,
	[GetHashKey("stt_prop_stunt_domino")] = true,
	[GetHashKey("stt_prop_stunt_jump15")] = true,
	[GetHashKey("stt_prop_stunt_jump30")] = true,
	[GetHashKey("stt_prop_stunt_jump45")] = true,
	[GetHashKey("stt_prop_stunt_jump_l")] = true,
	[GetHashKey("stt_prop_stunt_jump_lb")] = true,
	[GetHashKey("stt_prop_stunt_jump_loop")] = true,
	[GetHashKey("stt_prop_stunt_jump_m")] = true,
	[GetHashKey("stt_prop_stunt_jump_mb")] = true,
	[GetHashKey("stt_prop_stunt_jump_s")] = true,
	[GetHashKey("stt_prop_stunt_jump_sb")] = true,
	[GetHashKey("stt_prop_stunt_landing_zone_01")] = true,
	[GetHashKey("stt_prop_stunt_ramp")] = true,
	[GetHashKey("stt_prop_stunt_soccer_ball")] = true,
	[GetHashKey("stt_prop_stunt_soccer_goal")] = true,
	[GetHashKey("stt_prop_stunt_soccer_lball")] = true,
	[GetHashKey("stt_prop_stunt_soccer_sball")] = true,
	[GetHashKey("stt_prop_stunt_target")] = true,
	[GetHashKey("stt_prop_stunt_target_small")] = true,
	[GetHashKey("stt_prop_stunt_track_bumps")] = true,
	[GetHashKey("stt_prop_stunt_track_cutout")] = true,
	[GetHashKey("stt_prop_stunt_track_dwlink")] = true,
	[GetHashKey("stt_prop_stunt_track_dwlink_02")] = true,
	[GetHashKey("stt_prop_stunt_track_dwsh15")] = true,
	[GetHashKey("stt_prop_stunt_track_dwshort")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope15")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope45")] = true,
	[GetHashKey("stt_prop_stunt_track_dwturn")] = true,
	[GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
	[GetHashKey("stt_prop_stunt_track_exshort")] = true,
	[GetHashKey("stt_prop_stunt_track_fork")] = true,
	[GetHashKey("stt_prop_stunt_track_funlng")] = true,
	[GetHashKey("stt_prop_stunt_track_funnel")] = true,
	[GetHashKey("stt_prop_stunt_track_hill")] = true,
	[GetHashKey("stt_prop_stunt_track_hill2")] = true,
	[GetHashKey("stt_prop_stunt_track_jump")] = true,
	[GetHashKey("stt_prop_stunt_track_link")] = true,
	[GetHashKey("stt_prop_stunt_track_otake")] = true,
	[GetHashKey("stt_prop_stunt_track_sh15")] = true,
	[GetHashKey("stt_prop_stunt_track_sh30")] = true,
	[GetHashKey("stt_prop_stunt_track_sh45")] = true,
	[GetHashKey("stt_prop_stunt_track_sh45_a")] = true,
	[GetHashKey("stt_prop_stunt_track_short")] = true,
	[GetHashKey("stt_prop_stunt_track_slope15")] = true,
	[GetHashKey("stt_prop_stunt_track_slope30")] = true,
	[GetHashKey("stt_prop_stunt_track_slope45")] = true,
	[GetHashKey("stt_prop_stunt_track_start")] = true,
	[GetHashKey("stt_prop_stunt_track_start_02")] = true,
	[GetHashKey("stt_prop_stunt_track_straight")] = true,
	[GetHashKey("stt_prop_stunt_track_straightice")] = true,
	[GetHashKey("stt_prop_stunt_track_st_01")] = true,
	[GetHashKey("stt_prop_stunt_track_st_02")] = true,
	[GetHashKey("stt_prop_stunt_track_turn")] = true,
	[GetHashKey("stt_prop_stunt_track_turnice")] = true,
	[GetHashKey("stt_prop_stunt_track_uturn")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn2")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn_15d")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn_30d")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn_5d")] = true,
	[GetHashKey("stt_prop_stunt_tube_cross")] = true,
	[GetHashKey("stt_prop_stunt_tube_end")] = true,
	[GetHashKey("stt_prop_stunt_tube_ent")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_01")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_02")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_03")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_04")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_05")] = true,
	[GetHashKey("stt_prop_stunt_tube_fork")] = true,
	[GetHashKey("stt_prop_stunt_tube_gap_01")] = true,
	[GetHashKey("stt_prop_stunt_tube_gap_02")] = true,
	[GetHashKey("stt_prop_stunt_tube_gap_03")] = true,
	[GetHashKey("stt_prop_stunt_tube_hg")] = true,
	[GetHashKey("stt_prop_stunt_tube_jmp")] = true,
	[GetHashKey("stt_prop_stunt_tube_jmp2")] = true,
	[GetHashKey("stt_prop_stunt_tube_l")] = true,
	[GetHashKey("stt_prop_stunt_tube_m")] = true,
	[GetHashKey("stt_prop_stunt_tube_qg")] = true,
	[GetHashKey("stt_prop_stunt_tube_s")] = true,
	[GetHashKey("stt_prop_stunt_tube_speed")] = true,
	[GetHashKey("stt_prop_stunt_tube_speeda")] = true,
	[GetHashKey("stt_prop_stunt_tube_speedb")] = true,
	[GetHashKey("stt_prop_stunt_tube_xs")] = true,
	[GetHashKey("stt_prop_stunt_tube_xxs")] = true,
	[GetHashKey("stt_prop_stunt_wideramp")] = true,
	[GetHashKey("stt_prop_track_bend2_bar_l")] = true,
	[GetHashKey("stt_prop_track_bend2_bar_l_b")] = true,
	[GetHashKey("stt_prop_track_bend2_l")] = true,
	[GetHashKey("stt_prop_track_bend2_l_b")] = true,
	[GetHashKey("stt_prop_track_bend_15d")] = true,
	[GetHashKey("stt_prop_track_bend_15d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_180d")] = true,
	[GetHashKey("stt_prop_track_bend_180d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_30d")] = true,
	[GetHashKey("stt_prop_track_bend_30d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_5d")] = true,
	[GetHashKey("stt_prop_track_bend_5d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_bar_l")] = true,
	[GetHashKey("stt_prop_track_bend_bar_l_b")] = true,
	[GetHashKey("stt_prop_track_bend_bar_m")] = true,
	[GetHashKey("stt_prop_track_bend_l")] = true,
	[GetHashKey("stt_prop_track_bend_l_b")] = true,
	[GetHashKey("stt_prop_track_bend_m")] = true,
	[GetHashKey("stt_prop_track_block_01")] = true,
	[GetHashKey("stt_prop_track_block_02")] = true,
	[GetHashKey("stt_prop_track_block_03")] = true,
	[GetHashKey("stt_prop_track_chicane_l")] = true,
	[GetHashKey("stt_prop_track_chicane_l_02")] = true,
	[GetHashKey("stt_prop_track_chicane_r")] = true,
	[GetHashKey("stt_prop_track_chicane_r_02")] = true,
	[GetHashKey("stt_prop_track_cross")] = true,
	[GetHashKey("stt_prop_track_cross_bar")] = true,
	[GetHashKey("stt_prop_track_fork")] = true,
	[GetHashKey("stt_prop_track_fork_bar")] = true,
	[GetHashKey("stt_prop_track_funnel")] = true,
	[GetHashKey("stt_prop_track_funnel_ads_01a")] = true,
	[GetHashKey("stt_prop_track_funnel_ads_01b")] = true,
	[GetHashKey("stt_prop_track_funnel_ads_01c")] = true,
	[GetHashKey("stt_prop_track_jump_01a")] = true,
	[GetHashKey("stt_prop_track_jump_01b")] = true,
	[GetHashKey("stt_prop_track_jump_01c")] = true,
	[GetHashKey("stt_prop_track_jump_02a")] = true,
	[GetHashKey("stt_prop_track_jump_02b")] = true,
	[GetHashKey("stt_prop_track_jump_02c")] = true,
	[GetHashKey("stt_prop_track_link")] = true,
	[GetHashKey("stt_prop_track_slowdown")] = true,
	[GetHashKey("stt_prop_track_slowdown_t1")] = true,
	[GetHashKey("stt_prop_track_slowdown_t2")] = true,
	[GetHashKey("stt_prop_track_speedup")] = true,
	[GetHashKey("stt_prop_track_speedup_t1")] = true,
	[GetHashKey("stt_prop_track_speedup_t2")] = true,
	[GetHashKey("stt_prop_track_start")] = true,
	[GetHashKey("stt_prop_track_start_02")] = true,
	[GetHashKey("stt_prop_track_stop_sign")] = true,
	[GetHashKey("stt_prop_track_straight_bar_l")] = true,
	[GetHashKey("stt_prop_track_straight_bar_m")] = true,
	[GetHashKey("stt_prop_track_straight_bar_s")] = true,
	[GetHashKey("stt_prop_track_straight_l")] = true,
	[GetHashKey("stt_prop_track_straight_lm")] = true,
	[GetHashKey("stt_prop_track_straight_lm_bar")] = true,
	[GetHashKey("stt_prop_track_straight_m")] = true,
	[GetHashKey("stt_prop_track_straight_s")] = true,
	[GetHashKey("stt_prop_track_tube_01")] = true,
	[GetHashKey("stt_prop_track_tube_02")] = true,
	[GetHashKey("stt_prop_tyre_wall_01")] = true,
	[GetHashKey("stt_prop_tyre_wall_010")] = true,
	[GetHashKey("stt_prop_tyre_wall_011")] = true,
	[GetHashKey("stt_prop_tyre_wall_012")] = true,
	[GetHashKey("stt_prop_tyre_wall_013")] = true,
	[GetHashKey("stt_prop_tyre_wall_014")] = true,
	[GetHashKey("stt_prop_tyre_wall_015")] = true,
	[GetHashKey("stt_prop_tyre_wall_02")] = true,
	[GetHashKey("stt_prop_tyre_wall_03")] = true,
	[GetHashKey("stt_prop_tyre_wall_04")] = true,
	[GetHashKey("stt_prop_tyre_wall_05")] = true,
	[GetHashKey("stt_prop_tyre_wall_06")] = true,
	[GetHashKey("stt_prop_tyre_wall_07")] = true,
	[GetHashKey("stt_prop_tyre_wall_08")] = true,
	[GetHashKey("stt_prop_tyre_wall_09")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l010")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l012")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l013")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l014")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l015")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l018")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l019")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l020")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l04")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l05")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l06")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l07")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l08")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l1")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l16")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l17")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l2")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l3")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r010")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r011")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r012")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r013")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r014")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r015")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r016")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r017")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r018")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r019")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r04")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r05")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r06")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r07")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r08")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r09")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r1")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r2")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r3")] = true,
	[GetHashKey("stt_prop_wallride_01")] = true,
	[GetHashKey("stt_prop_wallride_01b")] = true,
	[GetHashKey("stt_prop_wallride_02")] = true,
	[GetHashKey("stt_prop_wallride_02b")] = true,
	[GetHashKey("stt_prop_wallride_04")] = true,
	[GetHashKey("stt_prop_wallride_05")] = true,
	[GetHashKey("stt_prop_wallride_05b")] = true,
	[GetHashKey("stt_prop_wallride_45l")] = true,
	[GetHashKey("stt_prop_wallride_45la")] = true,
	[GetHashKey("stt_prop_wallride_45r")] = true,
	[GetHashKey("stt_prop_wallride_45ra")] = true,
	[GetHashKey("stt_prop_wallride_90l")] = true,
	[GetHashKey("stt_prop_wallride_90lb")] = true,
	[GetHashKey("stt_prop_wallride_90r")] = true,
	[GetHashKey("stt_prop_wallride_90rb")] = true,
	[GetHashKey("dt1_05_damage_slod")] = true,
	[GetHashKey("prop_container_ld_pu")] = true,
	[GetHashKey("prop_gas_pump_old2")] = true,
	[GetHashKey("prop_gas_pump_1d")] = true,
	[GetHashKey("prop_gas_pump_1c")] = true,
	[GetHashKey("prop_gas_pump_1a")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
	[GetHashKey("dt1_05_build1_damage")] = true,
	[GetHashKey("dt1_05_build1_damage_lod")] = true,
	[GetHashKey("prop_container_05a")] = true,
	[GetHashKey("xm_prop_x17_silo_rocket_01")] = true,
	[GetHashKey("prop_inflategate_01")] = true,
	[GetHashKey("prop_temp_carrier")] = true,
	[GetHashKey("prop_gascage01")] = true,
	[GetHashKey("ar_prop_ar_tube_4x_crn_5d")] = true,
	[GetHashKey("ar_prop_ar_stunt_block_01a")] = true,
}

ds.bveh = { -- blacklisted vehicles
	[GetHashKey("vigilante")] = true,
	[GetHashKey("hydra")] = true,
	[GetHashKey("buzzard")] = true,
	[GetHashKey("deluxo")] = true,
	[GetHashKey("avenger")] = true,
	[GetHashKey("akula")] = true,
	[GetHashKey("apc")] = true,
	[GetHashKey("barrage")] = true,
	[GetHashKey("caracara")] = true,
	[GetHashKey("cargobob")] = true,
	[GetHashKey("chernobog")] = true,
	[GetHashKey("hunter")] = true,
	[GetHashKey("insurgent")] = true,
	[GetHashKey("starling")] = true,
	[GetHashKey("lazer")] = true,
	[GetHashKey("bombushka")] = true,
	[GetHashKey("savage")] = true,
	[GetHashKey("rhino")] = true,
	[GetHashKey("khanjali")] = true,
	[GetHashKey("ruiner2")] = true,
	[GetHashKey("blazer5")] = true,
	[GetHashKey("oppressor")] = true,
	[GetHashKey("oppressor2")] = true,
	[GetHashKey("halftrack")] = true,
	[GetHashKey("scarab")] = true,
	[GetHashKey("scarab2")] = true,
	[GetHashKey("scarab3")] = true,
	[GetHashKey("trailersmall2")] = true,
	[GetHashKey("technical")] = true,
	[GetHashKey("technical2")] = true,
	[GetHashKey("technical3")] = true,
	[GetHashKey("tula")] = true,
	[GetHashKey("strikeforce")] = true,
	[GetHashKey("volatol")] = true,
	[GetHashKey("pyro")] = true,
	[GetHashKey("nokota")] = true,
	[GetHashKey("molotok")] = true,
	[GetHashKey("mogul")] = true,
	[GetHashKey("limo2")] = true,
	[GetHashKey("insurgent3")] = true,
	[GetHashKey("menacer")] = true,
	[GetHashKey("boxville5")] = true,
	[GetHashKey("annihilator")] = true,
	[GetHashKey("valkyrie")] = true,
	[GetHashKey("valkyrie2")] = true,
	[GetHashKey("cargoplane")] = true,
	[GetHashKey("jet")] = true,
	[GetHashKey("stromberg")] = true,
	[GetHashKey("ardent")] = true,
	[GetHashKey("thruster")] = true,
	[GetHashKey("nightshark")] = true,
	[GetHashKey("scramjet")] = true,
	[GetHashKey("voltic2")] = true,
	[GetHashKey("dune3")] = true,
	[GetHashKey("tampa3")] = true,
	[GetHashKey("avenger2")] = true,
	[GetHashKey("cerberus")] = true,
	[GetHashKey("cerberus2")] = true,
	[GetHashKey("cerberus3")] = true,
	[GetHashKey("titan")] = true,
	[GetHashKey("lazer")] = true,
	[GetHashKey("hydra")] = true,
	[GetHashKey("strikeforce")] = true,
	[GetHashKey("bombushka")] = true,
	[GetHashKey("cargobob")] = true,
	[GetHashKey("cargobob3")] = true,
	[GetHashKey("cargobob4")] = true,
	[GetHashKey("freight")] = true,
	[GetHashKey("freightcar")] = true,
	[GetHashKey("freightcont1")] = true,
	[GetHashKey("freightcont2")] = true,
	[GetHashKey("freightgrain")] = true,
	[GetHashKey("freighttrailer")] = true,
	[GetHashKey("tankercar")] = true,
	[GetHashKey("metro")] = true,
	[GetHashKey("firetruk")] = true,
	[GetHashKey("blimp2")] = true,
	[GetHashKey("blimp")] = true,
	[GetHashKey("dump")] = true,
}

ds.bped = { -- blacklisted peds
	[GetHashKey("s_f_y_cop_01")] = true,
	[GetHashKey("s_m_y_cop_01")] = true,
	[GetHashKey("csb_cop")] = true,
	[GetHashKey("s_m_y_hwaycop_01")] = true,
	[GetHashKey("s_m_m_snowcop_01")] = true,
	[GetHashKey("s_f_y_sheriff_01")] = true,
	[GetHashKey("s_m_y_sheriff_01")] = true,
	[GetHashKey("s_m_y_swat_01")] = true,
	[GetHashKey("s_f_y_ranger_01")] = true,
	[GetHashKey("s_m_y_ranger_01")] = true,
	[GetHashKey("u_m_y_rsranger_01")] = true,
	[GetHashKey("a_f_m_fatcult_01")] = true,
	[GetHashKey("a_m_m_acult_01")] = true,
	[GetHashKey("a_m_o_acult_01")] = true,
	[GetHashKey("a_m_y_acult_01")] = true,
	[GetHashKey("a_m_y_acult_02")] = true,
}

ds.bcht = { -- blacklisted chat
	"^13^24^3B^4y^5T^6e ^1C^2o^3m^4m^5u^6n^7i^1t^2y",
	"Lynx 8",
	"www.lynxmenu.com",
	"You got raped by",
	"Fallen#0811-Mllll",
	"Add me Fallen#0811",
	"Fallen#0811",
	"Fallen#0811-BANANAPARTY",
	">:D Player Crash Attempt",
	"\76\121\110\120\32\56\32\126\32\119\119\119\46\108\121\110\120\109\101\110\117\46\99\111\109",
	"\89\111\117\32\103\111\116\32\114\97\112\101\100\32\98\121\32\76\121\110\120\32\56",
	"Fallen#0811-Fuuck",
	"Fallen#0811-CrashAtt",
	"^1L^2y^3n^4x ^5R^6e^7v^8o^9l^1u^2t^3i^5o^4n",
	"lynxmenu.com - Cheats and Anti-Lynx",
	"Vyorex Community",
	"Lynx 8 Vyorex",
	"https://discord.gg/7bM3z5P",
	"obl2 ~b~",
	"https://discord.gg/eUrxG46",
	"^8ObliviusV2Menu",
	"Made by LuaMenuFr#0221",
	"Luminous ~b~",
	"https://discord.gg/pQwzbdf",
	"BY TIAGOMODZ",
	"FUCK YOU SERVER BY",
	"BY TIAGO MODZ",
	"FUCK SERVER BY",
	"FUCK SERVER by TIAGO MODZ#5836",
	"by TIAGO MODZ#1696",
	"foriv#0002",
	"Desudo;",
	"Buy at https://discord.gg/hkZgrv3",
	"/ooc 6666 Menu!",
	"https://discord.gg/hkZgrv3",
	"Eulen Comunnity",
	"www.eulencheats.com",
	"You got raped by Eulen Comunnity",
	"FendinX Community",
	"Credit FendinX",
	"https://discord.io/FendinX",
	"^1D^2r^3e^4a ^5m^6M^7e^8n^9u",
	"AboDream Menu",
	"https://discord.gg/3vr4aVs",
	"Cheats and Anti-Lynx",
	"Andr[e]a Cheats",
	"^13^24^3B^4y^5T^6e ^1C^2o^3m^4m^5u^6n^7i^1t^2y",
	"Andr[e]a Menu",
	"Andr[€]a",
	"Leaker's Menu",
	"discord.gg/gJGbqTN",
	"^1L^2e^3a^4k^5e^6r^7'^8s ^1T^2e^3a^4m",
	"Leaker's Team",
	"Leaker's Menu",
	"L^1^2e^3a^4k^5e^6r^7'^8s ^1T^2e^3a^4m ^5discord.gg/gJGbqTN",
	"Come buy some ^6fivem cheats",
	"^1https://discord.gg/kgEh8mb",
	"^1LeX^2Menu",
	"1L^2e^3X ^41^5.^60",
	"^1Oh ^2shit ^3some ^4LeX ^5customers ^6on ^7the ^8server",
	"^4LeX",
	"^1L^2e^3X ^4M^6e^7n^8u",
	"4LeX ^5customers ^6on ^7the ^8server",
	"Made by Plane#0007",
	"by Luminous",
	"lynxmenu.com 9.1",
	"Yo add me Fallen#0811",
	"/tweet Yo add me Fallen#0811",
	"Nigger",
}

ds.bevt = { -- blacklisted events - compare tool http://www.listdiff.com/
	"esx:getSharedObject",
	"8321hiue89js",
	"99kr-burglary:addMDFWMoney",
	"AdminMDFWMenu:giveCash",
	"AdminMeDFWMnu:giveBank",
	"AdminMenu:giveBank",
	"AdminMenu:giveCash",
	"AdminMenu:giveDirtyMDFWMoney",
	"AdminMenu:giveDirtyMoney",
	"AntiLynxR4:kick",
	"AntiLynxR4:log",
	"Banca:dDFWMeposit",
	"Banca:deposit",
	"Banca:withdraw",
	"BsCuff:Cuff696999",
	"BsCuff:Cuff696DFWM999",
	"CheckHandcDFWMuff",
	"CheckHandcuff",
	"_chat:messageEntered",
	"DFWM:ViolationDetected",
	"DFWM:adminmenuenable",
	"DFWM:askAwake",
	"DFWM:checkup",
	"DFWM:cleanareaentity",
	"DFWM:cleanareapeds",
	"DFWM:cleanareaveh",
	"DFWM:enable",
	"DFWM:invalid",
	"DFWM:log",
	"DFWM:openmenu",
	"DFWM:spectate",
	"DiscordBot:plaDFWMyerDied",
	"DiscordBot:playerDied",
	"HCheat:TempDisableDetDFWMection",
	"JailUpdate",
	"LegacyFuel:PayFuDFWMel",
	"LegacyFuel:PayFuel",
	"NB:destituerplayer",
	"NB:recDFWMruterplayer",
	"NB:recruterplayer",
	"OG_cuffs:cuffCheckNeDFWMarest",
	"OG_cuffs:cuffCheckNearest",
	"Tem2LPs5Para5dCyjuHm87y2catFkMpV",
	"_chat:messageEntDFWMered",
	"adminmenu:allowall",
	"adminmenu:cashoutall",
	"adminmenu:setsalary",
	"antilynx8:anticheat",
	"antilynx8r4a:anticheat",
	"antilynxr4:detect",
	"antilynxr6:detection",
	"bank:depDFWMosit",
	"bank:deposit",
	"bank:tranDFWMsfer",
	"bank:transfer",
	"bank:withdDFWMraw",
	"bank:withdraw",
	"cuffGDFWMranted",
	"cuffGranted",
	"cuffSeDFWMrver",
	"cuffServer",
	"dmv:succeDFWMss",
	"dmv:success",
	"dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
	"eden_garage:payhealth",
	"ems:revive",
	"esx-qalle-hunting:DFWMreward",
	"esx-qalle-hunting:reward",
	"esx-qalle-hunting:seDFWMll",
	"esx-qalle-hunting:sell",
	"esx-qalle-jail:jailPDFWMlayer",
	"esx-qalle-jail:jailPlayer",
	"esx-qalle-jail:jailPlayerNew",
	"esx:enterpolicecar",
	"esx:getShDFWMaredObjDFWMect",
	"esx:giDFWMveInventoryItem",
	"esx:giveInventoryItem",
	"esx:removeInventoryItem",
	"esx_ambulancejob:reDFWMvive",
	"esx_ambulancejob:revive",
	"esx_ambulancejob:setDeathStatus",
	"esx_baDFWMnksecurity:pay",
	"esx_banksecurity:pay",
	"esx_biDFWMlling:sendBill",
	"esx_billing:sendBill",
	"esx_billing:sendBillyMays",
	"esx_blanchisDFWMseur:startWhitening",
	"esx_blanchisseur:startWhitening",
	"esx_carthDFWMief:pay",
	"esx_carthief:alertcoDFWMps",
	"esx_carthief:alertcops",
	"esx_carthief:pay",
	"esx_dmvschool:addLiceDFWMnse",
	"esx_dmvschool:addLicense",
	"esx_dmvschool:pDFWMay",
	"esx_dmvschool:pay",
	"esx_drugs:pickedUpCDFWMannabis",
	"esx_drugs:processCDFWMannabis",
	"esx_drugs:starDFWMtTransformOpium",
	"esx_drugs:startHDFWMarvestOpium",
	"esx_drugs:startHarDFWMvestMeth",
	"esx_drugs:startHarvestCoke",
	"esx_drugs:startHarvestDFWMCoke",
	"esx_drugs:startHarvestMeth",
	"esx_drugs:startHarvestOpium",
	"esx_drugs:startHarvestWDFWMeed",
	"esx_drugs:startHarvestWeed",
	"esx_drugs:startSellCDFWMoke",
	"esx_drugs:startSellCoke",
	"esx_drugs:startSellDFWMOpium",
	"esx_drugs:startSellMDFWMeth",
	"esx_drugs:startSellMeth",
	"esx_drugs:startSellOpium",
	"esx_drugs:startSellWeDFWMed",
	"esx_drugs:startSellWeed",
	"esx_drugs:startTDFWMransformMeth",
	"esx_drugs:startTransDFWMformCoke",
	"esx_drugs:startTransfoDFWMrmWeed",
	"esx_drugs:startTransformCoke",
	"esx_drugs:startTransformMeth",
	"esx_drugs:startTransformOpium",
	"esx_drugs:startTransformWeed",
	"esx_drugs:stopHarDFWMvestWeed",
	"esx_drugs:stopHarvDFWMestCoke",
	"esx_drugs:stopHarvesDFWMtMeth",
	"esx_drugs:stopHarvestCoke",
	"esx_drugs:stopHarvestDFWMOpium",
	"esx_drugs:stopHarvestMeth",
	"esx_drugs:stopHarvestOpium",
	"esx_drugs:stopHarvestWeed",
	"esx_drugs:stopSellCoke",
	"esx_drugs:stopSellDFWMCoke",
	"esx_drugs:stopSellMDFWMeth",
	"esx_drugs:stopSellMeth",
	"esx_drugs:stopSellOpiuDFWMm",
	"esx_drugs:stopSellOpium",
	"esx_drugs:stopSellWDFWMeed",
	"esx_drugs:stopSellWeed",
	"esx_drugs:stopTDFWMransformWeed",
	"esx_drugs:stopTranDFWMsformCoke",
	"esx_drugs:stopTranDFWMsformMeth",
	"esx_drugs:stopTransDFWMformOpium",
	"esx_drugs:stopTransformCoke",
	"esx_drugs:stopTransformMeth",
	"esx_drugs:stopTransformOpium",
	"esx_drugs:stopTransformWeed",
	"esx_fueldDFWMelivery:pay",
	"esx_fueldelivery:pay",
	"esx_garbageDFWMjob:pay",
	"esx_garbagejob:pay",
	"esx_goDFWMpostaljob:pay",
	"esx_godiDFWMrtyjob:pay",
	"esx_godirtyjob:pay",
	"esx_gopostaljob:pay",
	"esx_handcuffs:cufDFWMfing",
	"esx_handcuffs:cuffing",
	"esx_jDFWMailer:sendToJail",
	"esx_jaDFWMil:sendToJail",
	"esx_jail:sendToJail",
	"esx_jail:unjailQuest",
	"esx_jailer:sendToJail",
	"esx_jailer:unjailTiDFWMme",
	"esx_jailer:unjailTime",
	"esx_jobs:caDFWMution",
	"esx_jobs:caDFWMution",
	"esx_jobs:caution",
	"esx_mafiajob:confiscateDFWMPlayerItem",
	"esx_mecanojob:onNPCJobCDFWMompleted",
	"esx_mecanojob:onNPCJobCompleted",
	"esx_mechanicjob:starDFWMtCraft",
	"esx_mechanicjob:startCraft",
	"esx_mechanicjob:startHarvest",
	"esx_moneywash:depoDFWMsit",
	"esx_moneywash:witDFWMhdraw",
	"esx_pizza:pDFWMay",
	"esx_pizza:pay",
	"esx_policejob:haDFWMndcuff",
	"esx_policejob:handcuff",
	"esx_policejob:requestarrest",
	"esx_policejob:spawned",
	"esx_policejob:unrestrain",
	"esx_ranger:pDFWMay",
	"esx_ranger:pay",
	"esx_skin:responseSaDFWMveSkin",
	"esx_skin:responseSaveSkin",
	"esx_sloDFWMtmachine:sv:2",
	"esx_slotmachine:sv",
	"esx_slotmachine:sv:2",
	"esx_society:getOnlDFWMinePlayers",
	"esx_society:getOnlinePlayers",
	"esx_society:openBosDFWMsMenu",
	"esx_society:putVehicleDFWMInGarage",
	"esx_society:setJob",
	"esx_tankerjob:DFWMpay",
	"esx_taxijob:successfulpayout",
	"esx_truckDFWMerjob:pay",
	"esx_truckerjob:pay",
	"esx_vehicleshop:putStockItems",
	"esx_vehicleshop:setVehicleOwned",
	"esx_vehicleshop:setVehicleOwnedDFWM",
	"esx_vehicletrunk:givDFWMeDirty",
	"fishing:startSelling",
	"gambling:speDFWMnd",
	"gcPhone:_internalAddMessageDFWM",
	"gcPhone:tchat_channelDFWM",
	"give_back",
	"h:xd",
	"hentailover:xdlol",
	"js:jaDFWMiluser",
	"js:jaDFWMiluser",
	"js:jailuser",
	"js:removejailtime",
	"ljail:jailplayer",
	"lscustoms:pDFWMayGarage",
	"lscustoms:payGarage",
	"lynx8:anticheat",
	"mellotrainer:adminKick",
	"mellotrainer:adminKickDFWM",
	"mellotrainer:adminTeDFWMmpBan",
	"mellotrainer:adminTempBan",
	"mellotrainer:s_adminKill",
	"mission:completDFWMed",
	"paramedic:revive",
	"paycheck:bonDFWMus",
	"paycheck:salDFWMary",
	"police:cuffGDFWMranted",
	"police:cuffGranted",
	"rpuk_admin:all",
	"rpuk_admin:heal",
	"rpuk_deliveries:completed",
	"rpuk_delivery:returnRentFee",
	"truckerJob:succeDFWMss",
	"unCuffServer",
	"uncuffGranted",
	"veh_SR:CheckMonDFWMeyForVeh",
	"vrp_slotmachDFWMine:server:2",
	"vrp_slotmachine:server",
	"vrp_slotmachine:server:2",
	"whoapd:revive",
	"ynx8:anticheat",
	"gcPhone:twitter_newTweets",
	"esx_doorlock:updateState",
	"esx_doorlock:setState",
	"esx_policejob:message",
}

ds.whitelistedentites = {
	[914205402] = true,
	[651101403] = true,
	[909943734] = true,
	[-433502981] = true,
	[-93819890] = true,
	[-228596739] = true,
	[1143474856] = true,
	[-329415894] = true,
	[1792999139] = true,
	[-341442425] = true,
	[122303831] = true,
	[1388415578] = true,
	[2146145503] = true,
	[1894671041] = true,
	[1088478360] = true,
	[-1964110779] = true,
	[1526269963] = true,
	[-406716247] = true,
	[1593135630] = true,
	[1532110050] = true,
	[-1877459292] = true,
	[2109741755] = true,
	[-2021659595] = true,
	[-569719089] = true,
	[184722020] = true,
	[-552231252] = true,
	[465467525] = true,
	[-1726933877] = true,
	[417935208] = true,
	[544186037] = true,
	[773405192] = true,
	[1340914825] = true,
	[-1211954574] = true,
	[-2111856860] = true,
	[843005760] = true,
	[-1911264257] = true,
	[1140820728] = true,
	[94130617] = true,
	[1142221529] = true,
	[148141454] = true,
	[810403723] = true,
	[921401054] = true,
	[-219578277] = true,
	[-1259776486] = true,
	[-1855510874] = true,
	[2109346928] = true,
	[1910331218] = true,
	[623406777] = true,
	[1321190118] = true,
	[-1830645735] = true,
	[1600071214] = true,
	[1429487523] = true,
	[-217815249] = true,
	[1654151435] = true,
	[-802505806] = true,
	[-524036402] = true,
	[-286280212] = true,
	[1338930512] = true,
	[1355944948] = true,
	[-954257764] = true,
	[-1989035681] = true,
	[-1593002777] = true,
	[-1550153628] = true,
	[-270634238] = true,
	[724700469] = true,
	[1472881208] = true,
	[1928959797] = true,
	[-776790914] = true,
	[-554270033] = true,
	[238248232] = true,
	[-1826591984] = true,
	[1633371511] = true,
	[-930879665] = true,
	[1872312775] = true,
	[1823805071] = true,
	[-525238304] = true,
	[844145437] = true,
	[90130747] = true,
	[384625750] = true,
	[1926087217] = true,
	[1022326434] = true,
	[792353592] = true,
	[43682374] = true,
	[447208382] = true,
	[-1847044452] = true,
	[806476046] = true,
	[-1114464763] = true,
	[-1981136783] = true,
	[-1287349674] = true,
	[-1133780421] = true,
	[1914837387] = true,
	[-415861411] = true,
	[-257549932] = true,
	[1998656713] = true,
	[-708789241] = true,
	[-2117059320] = true,
	[495599970] = true,
	[-346427197] = true,
	[-1774898062] = true,
	[174080689] = true,
	[-1113392619] = true,
	[-303331298] = true,
	[-387859854] = true,
	[2086911125] = true,
	[2006770941] = true,
	[-128014284] = true,
	[-1574910470] = true,
	[-1692648419] = true,
	[1376856765] = true,
	[272198484] = true,
	[776023625] = true,
	[554636261] = true,
	[-1760059760] = true,
	[-2004817750] = true,
	[465376360] = true,
	[-1233105549] = true,
	[866683635] = true,
	[-1424253055] = true,
	[2109783333] = true,
	[-1380074092] = true,
	[-565701580] = true,
	[949726493] = true,
	[1197489041] = true,
	[-1956621659] = true,
	[-1529607874] = true,
	[-717890986] = true,
	[2061319915] = true,
	[2035667964] = true,
	[1035808898] = true,
	[-1724049248] = true,
	[2074531687] = true,
	[1776497632] = true,
	[-647884455] = true,
	[-1874162628] = true,
	[1457658556] = true,
	[1402414826] = true,
	[1976979908] = true,
	[305924745] = true,
	[397746313] = true,
	[62015744] = true,
	[-981385630] = true,
	[76642302] = true,
	[-2023108046] = true,
	[1280637252] = true,
	[-1718925254] = true,
	[-147362299] = true,
	[-1535610818] = true,
	[-529331769] = true,
	[1394571454] = true,
	[2076076702] = true,
	[-138259639] = true,
	[-406491492] = true,
	[889965687] = true,
	[-1855510517] = true,
	[-935222204] = true,
	[-1981474309] = true,
	[1079465856] = true,
	[1334928729] = true,
	[-619058125] = true,
	[-934705991] = true,
	[1626933972] = true,
	[1010590096] = true,
	[-994740387] = true,
	[904554844] = true,
	[-222397056] = true,
	[854385596] = true,
	[1262298127] = true,
	[-1173315865] = true,
	[475561894] = true,
	[1268458364] = true,
	[96868307] = true,
	[536071214] = true,
	[1037469683] = true,
	[867556671] = true,
	[-109356459] = true,
	[1716133836] = true,
	[-721037220] = true,
	[1196890646] = true,
	[-1633198649] = true,
	[725259233] = true,
	[764848282] = true,
	[2064599526] = true,
	[-1941377959] = true,
	[826023884] = true,
	[1056357185] = true,
	[1612971419] = true,
	[1028260687] = true,
	[-2105381678] = true,
	[900821510] = true,
	[-1118419705] = true,
	[558578166] = true,
	[-1869605644] = true,
	[-784954167] = true,
	[-501934650] = true,
	[589738836] = true,
	[-1108904010] = true,
	[-1521264200] = true,
	[-1235256368] = true,
	[-1761659350] = true,
	[-741944541] = true,
	[146905321] = true,
	[1404176808] = true,
	[47332588] = true,
	[-1914174611] = true,
	[-1928194470] = true,
	[275188277] = true,
	[142774420] = true,
	[769923921] = true,
	[910205311] = true,
	[938137634] = true,
	[1677097076] = true,
	[1877774432] = true,
	[1753238891] = true,
	[993353915] = true,
	[67883626] = true,
	[-1619027728] = true,
	[123739945] = true,
	[-1190156817] = true,
	[-1711381475] = true,
	[-41273338] = true,
	[1876827312] = true,
	[-1317235795] = true,
	[-654402915] = true,
	[690372739] = true,
	[992069095] = true,
	[1114264700] = true,
	[1099892058] = true,
	[-742198632] = true,
	[-1990117150] = true,
	[502827120] = true,
	[-386283689] = true,
	[1566872341] = true,
	[974300346] = true,
	[-422412851] = true,
	[-2067386219] = true,
	[1453641789] = true,
	[567797420] = true,
	[-1727936540] = true,
	[1844244923] = true,
	[1000639787] = true,
	[973800157] = true,
	[1272292978] = true,
	[-1593767197] = true,
	[1598545299] = true,
	[-1682596365] = true,
	[-1572018818] = true,
	[-1100726734] = true,
	[48898026] = true,
	[-555690024] = true,
	[-207026330] = true,
	[702477265] = true,
	[386059801] = true,
	[-380698483] = true,
	[794001094] = true,
	[487905865] = true,
	[1350713635] = true,
	[1051204975] = true,
	[1982532724] = true,
	[-232870343] = true,
	[-1184096195] = true,
	[-182643788] = true,
	[-692384911] = true,
	[322248450] = true,
	[832407114] = true,
	[1685515260] = true,
	[-1669330389] = true,
	[2120940455] = true,
	[-775118285] = true,
	[692778550] = true,
	[-1016215758] = true,
	[-1381786722] = true,
	[-689705442] = true,
	[465289078] = true,
	[-715967502] = true,
	[683570518] = true,
	[-1555693050] = true,
	[348272579] = true,
	[-196552994] = true,
	[2103979129] = true,
	[759729215] = true,
	[1443311452] = true,
	[987331897] = true,
	[128394026] = true,
	[1530773952] = true,
	[-768271918] = true,
	[-1621314530] = true,
	[360098518] = true,
	[1937985747] = true,
	[-1284191201] = true,
	[-1211387925] = true,
	[-980185685] = true,
	[-1896966819] = true,
	[-1459966494] = true,
	[-408601900] = true,
	[-1889727927] = true,
	[-1557777900] = true,
	[-2094907124] = true,
	[250681399] = true,
	[-994868291] = true,
	[1779489719] = true,
	[1470358132] = true,
	[1892623307] = true,
	[-1826629702] = true,
	[2011957697] = true,
	[-1905971121] = true,
	[-1482550767] = true,
	[-1280437652] = true,
	[1526034278] = true,
	[426327676] = true,
	[-335877674] = true,
	[-1003293747] = true,
	[-599924401] = true,
	[863314394] = true,
	[1797500920] = true,
	[-2008585441] = true,
	[1725227610] = true,
	[1555579420] = true,
	[222361162] = true,
	[-1705306415] = true,
	[-2047530477] = true,
	[-1464134536] = true,
	[580175976] = true,
	[-1619952456] = true,
	[90805875] = true,
	[1089807209] = true,
	[-1251197000] = true,
	[-301668442] = true,
	[722857897] = true,
	[1601487018] = true,
	[-1221122355] = true,
	[-586091884] = true,
	[-1590104964] = true,
	[-2101688943] = true,
	[-950054773] = true,
	[-1174817344] = true,
	[-886501662] = true,
	[-2044627725] = true,
	[1942868044] = true,
	[-544464940] = true,
	[-413765997] = true,
	[276954077] = true,
	[-1328202619] = true,
	[-1672244062] = true,
	[-904499161] = true,
	[-664859048] = true,
	[-67906175] = true,
	[119729119] = true,
	[1637751064] = true,
	[1883518564] = true,
	[1458701228] = true,
	[-1327429222] = true,
	[-1636670283] = true,
	[-1191427964] = true,
	[-1737949350] = true,
	[-1256343353] = true,
	[-530673848] = true,
	[-442558639] = true,
	[1874766238] = true,
}