ds = {}

ds.bcmd = {
	"lol",
	"haha",
	"panickey",
	"chocolate",
	"pk",
	"killmenu",
	"menu",
	"porcodiooo",
	"demmerda",
	"puzzi",
}

ds.bwep = {
	"WEAPON_RAILGUN",
	"weapon_railgun",
	"WEAPON_GARBAGEBAG",
	"weapon_garbagebag",
	"WEAPON_RAYMINIGUN",
	"weapon_rayminigun",
	-- "WEAPON_GRENDADELAUNCHER",
	-- "weapon_grenadelauncher",
	"WEAPON_HOMINGLAUNCHER",
	"weapon_hominglauncher",
	"WEAPON_COMPACTLAUNCHER",
	"weapon_compactlauncher",
	"WEAPON_RAYCARBINE",
	"weapon_raycarbine",
	"WEAPON_RAYPISTOL",
	"weapon_raypistol",
	"WEAPON_STICKYBOMB",
	"weapon_stickybomb",
	"WEAPON_PIPEBOMB",
	"weapon_pipebomb",
	"WEAPON_GRENADE",
	"weapon_grenade",
	"WEAPON_HEAVYSNIPER_MK2",
	"weapon_heavysniper_mk2",
	"WEAPON_HEAVYSNIPER",
	"weapon_heavysniper",
	"WEAPON_MARKSMANRIFLE",
	"weapon_marksmanrifle",
	"WEAPON_MARKSMANRIFLE_MK2",
	"weapon_marksmanrifle_mk2",
	"WEAPON_MG",
	"weapon_mg",
	"WEAPON_COMBATMG",
	"weapon_combatmg",
	"WEAPON_COMBATMG_MK2",
	"weapon_combatmg_mk2",
	"WEAPON_RPG",
	"weapon_rpg",
	"WEAPON_MINIGUN",
	"weapon_minigun",
	"WEAPON_PROXMINE",
	"weapon_proxmine",
}

ds.bveh = { -- blacklisted vehicles
	[GetHashKey("vigilante")] = true,
	[GetHashKey("hydra")] = true,
	[GetHashKey("buzzard")] = true,
	[GetHashKey("deluxo")] = true,
	[GetHashKey("avenger")] = true,
	[GetHashKey("akula")] = true,
	[GetHashKey("apc")] = true,
	[GetHashKey("barrage")] = true,
	[GetHashKey("caracara")] = true,
	[GetHashKey("cargobob")] = true,
	[GetHashKey("chernobog")] = true,
	[GetHashKey("hunter")] = true,
	[GetHashKey("insurgent")] = true,
	[GetHashKey("starling")] = true,
	[GetHashKey("lazer")] = true,
	[GetHashKey("bombushka")] = true,
	[GetHashKey("savage")] = true,
	[GetHashKey("rhino")] = true,
	[GetHashKey("khanjali")] = true,
	[GetHashKey("ruiner2")] = true,
	[GetHashKey("blazer5")] = true,
	[GetHashKey("oppressor")] = true,
	[GetHashKey("oppressor2")] = true,
	[GetHashKey("halftrack")] = true,
	[GetHashKey("scarab")] = true,
	[GetHashKey("scarab2")] = true,
	[GetHashKey("scarab3")] = true,
	[GetHashKey("trailersmall2")] = true,
	[GetHashKey("technical")] = true,
	[GetHashKey("technical2")] = true,
	[GetHashKey("technical3")] = true,
	[GetHashKey("tula")] = true,
	[GetHashKey("strikeforce")] = true,
	[GetHashKey("volatol")] = true,
	[GetHashKey("pyro")] = true,
	[GetHashKey("nokota")] = true,
	[GetHashKey("molotok")] = true,
	[GetHashKey("mogul")] = true,
	[GetHashKey("limo2")] = true,
	[GetHashKey("insurgent3")] = true,
	[GetHashKey("menacer")] = true,
	[GetHashKey("boxville5")] = true,
	[GetHashKey("annihilator")] = true,
	[GetHashKey("valkyrie")] = true,
	[GetHashKey("valkyrie2")] = true,
	[GetHashKey("cargoplane")] = true,
	[GetHashKey("jet")] = true,
	[GetHashKey("stromberg")] = true,
	[GetHashKey("ardent")] = true,
	[GetHashKey("thruster")] = true,
	[GetHashKey("nightshark")] = true,
	[GetHashKey("scramjet")] = true,
	[GetHashKey("voltic2")] = true,
	[GetHashKey("dune3")] = true,
	[GetHashKey("tampa3")] = true,
	[GetHashKey("avenger2")] = true,
	[GetHashKey("cerberus")] = true,
	[GetHashKey("cerberus2")] = true,
	[GetHashKey("cerberus3")] = true,
	[GetHashKey("titan")] = true,
	[GetHashKey("lazer")] = true,
	[GetHashKey("hydra")] = true,
	[GetHashKey("strikeforce")] = true,
	[GetHashKey("bombushka")] = true,
	[GetHashKey("cargobob")] = true,
	[GetHashKey("cargobob3")] = true,
	[GetHashKey("cargobob4")] = true,
	[GetHashKey("freight")] = true,
	[GetHashKey("freightcar")] = true,
	[GetHashKey("freightcont1")] = true,
	[GetHashKey("freightcont2")] = true,
	[GetHashKey("freightgrain")] = true,
	[GetHashKey("freighttrailer")] = true,
	[GetHashKey("tankercar")] = true,
	[GetHashKey("metro")] = true,
	[GetHashKey("firetruk")] = true,
	[GetHashKey("blimp2")] = true,
	[GetHashKey("blimp")] = true,
	[GetHashKey("dump")] = true,
	[GetHashKey("tug")] = true,
}

ds.bnpl = {
	["Luminous"] = true, ["LynxMenu"] = true,
	["obl2"] = true, ["Tiago"] = true,
	["LYNX"] = true, ["Desudo"] = true,
	["eulencheats"] = true, ["HamHaxia"] = true
}